### ISSUE TITLE
tests fails to run

### ISSUE THREAD

**Issue by etam** [datapublica/pytrie3#1]
```
======================================================================
ERROR: Failure: ImportError (No module named 'UserDict')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.4/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/abuild/rpmbuild/BUILD/PyTrie3-0.2/test/test_mapping.py", line 9, in <module>
    import UserDict
ImportError: No module named 'UserDict'

======================================================================
ERROR: test_pickle (test_trie.TestTrie)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/PyTrie3-0.2/test/test_trie.py", line 77, in test_pickle
    for proto in xrange(HIGHEST_PROTOCOL):
NameError: name 'xrange' is not defined

======================================================================
FAIL: test_consistency_wprefix (test_trie.TestTrie)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/PyTrie3-0.2/test/test_trie.py", line 73, in test_consistency_wprefix
    zip(t.keys(prefix), t.values(prefix)))
AssertionError: <generator object generator at 0x7f07eded7828> != <zip object at 0x7f07edee1288>

======================================================================
FAIL: test_items_wprefix (test_trie.TestTrie)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/PyTrie3-0.2/test/test_trie.py", line 65, in test_items_wprefix
    [('all',2),('allot',3),('alloy',4),('aloe',5)])
AssertionError: <generator object generator at 0x7f07eded7e10> != [('all', 2), ('allot', 3), ('alloy', 4), ('aloe', 5)]

======================================================================
FAIL: test_values_wprefix (test_trie.TestTrie)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/PyTrie3-0.2/test/test_trie.py", line 59, in test_values_wprefix
    self.assertEqual(self.trie.values('al'), [2,3,4,5])
AssertionError: <generator object generator at 0x7f07edeecea0> != [2, 3, 4, 5]

----------------------------------------------------------------------
Ran 13 tests in 0.010s

FAILED (errors=2, failures=3)
```

**Comment by scharron** [comment]
Thanks, fixed !
